spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/testdb
        # proper database username and password should be added
        username: dbuser
        password: dbpassword
    
    liquibase:
      change-log: classpath:/db/changelog/changelog.sql
    
    jpa:
      generate-ddl: true
      show-sql: true
    
    web:
      resources:
        add-mappings: false
    
    mvc:
      throw-exception-if-no-handler-found: true
         
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false
    
  servlet:
    encoding:
       force: true

#   
    